#!/bin/bash

echo "🔧 Configuring Keycloak service on Render..."

echo "📊 Current service status:"
echo "   Service ID: srv-d3fo21p5pdvs73bgedjg"
echo "   URL: https://mandel-keycloak.onrender.com"
echo "   Dashboard: https://dashboard.render.com/web/srv-d3fo21p5pdvs73bgedjg"
echo ""
echo "⚠️  The service is currently using the wrong Dockerfile."
echo "   It's building the mint Dockerfile instead of Keycloak."
echo ""
echo "🔧 Manual configuration needed:"
echo ""
echo "1. Go to the Render dashboard:"
echo "   https://dashboard.render.com/web/srv-d3fo21p5pdvs73bgedjg/settings"
echo ""
echo "2. Update these settings:"
echo "   • Dockerfile Path: ./Dockerfile.keycloak"
echo "   • Root Directory: (leave empty)"
echo "   • Build Command: (leave empty)"
echo "   • Start Command: (leave empty)"
echo ""
echo "3. Environment variables (already set):"
echo "   ✅ KEYCLOAK_ADMIN=admin"
echo "   ✅ KEYCLOAK_ADMIN_PASSWORD=admin123"
echo "   ✅ KC_DB=dev-file"
echo "   ✅ KC_HTTP_PORT=8080"
echo "   ✅ KC_HOSTNAME_STRICT=false"
echo "   ✅ KC_HOSTNAME_STRICT_HTTPS=false"
echo "   ✅ KC_HTTP_ENABLED=true"
echo ""
echo "4. After updating, trigger a new deployment"
echo ""
echo "5. Test the service:"
echo "   curl https://mandel-keycloak.onrender.com/health/ready"
echo "   curl https://mandel-keycloak.onrender.com/realms/cashu-realm/.well-known/openid-configuration"
echo ""
echo "6. Update mint service environment:"
echo "   CDK_MINTD_AUTH_OPENID_DISCOVERY=https://mandel-keycloak.onrender.com/realms/cashu-realm/.well-known/openid-configuration"
echo ""
echo "✅ Once configured, your Keycloak service will be ready!"

