#!/bin/bash

echo "🚀 Deploying Keycloak to Render..."

# Check if we're in the right directory
if [ ! -f "keycloak/Dockerfile" ]; then
    echo "❌ Please run this script from the project root directory"
    exit 1
fi

echo "📊 Keycloak configuration:"
echo "   ✅ Dockerfile created for Keycloak"
echo "   ✅ Realm configuration with cashu-client"
echo "   ✅ Test user: testuser / testpass123"
echo "   ✅ Admin: admin / admin123"
echo ""
echo "🔧 Keycloak features:"
echo "   • OpenID Connect discovery endpoint"
echo "   • cashu-client configured"
echo "   • Test user for authentication"
echo "   • Realm: cashu-realm"
echo ""
echo "📝 To deploy Keycloak to Render:"
echo ""
echo "1. Create a new web service in Render dashboard:"
echo "   • Name: mandel-keycloak"
echo "   • Runtime: Docker"
echo "   • Build Command: (leave empty)"
echo "   • Start Command: (leave empty)"
echo "   • Root Directory: keycloak"
echo ""
echo "2. Set environment variables:"
echo "   • KEYCLOAK_ADMIN=admin"
echo "   • KEYCLOAK_ADMIN_PASSWORD=admin123"
echo "   • KC_DB=dev-file"
echo "   • KC_HTTP_PORT=8080"
echo "   • KC_HOSTNAME_STRICT=false"
echo "   • KC_HOSTNAME_STRICT_HTTPS=false"
echo "   • KC_HTTP_ENABLED=true"
echo ""
echo "3. Update mint service environment:"
echo "   • CDK_MINTD_AUTH_OPENID_DISCOVERY=https://mandel-keycloak.onrender.com/realms/cashu-realm/.well-known/openid-configuration"
echo ""
echo "4. Test locally first:"
echo "   docker-compose -f docker-compose.dev.yml up -d"
echo "   # Access Keycloak at http://localhost:8080"
echo "   # Access mint at http://localhost:3338"
echo ""
echo "✅ After deployment, your mint will support NUT-22 authentication!"
