version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak}
    volumes:
      - keycloak-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: ["start-dev", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KEYCLOAK_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HTTP_PORT: 8080
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      - postgres
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import
    ports:
      - "8081:8080"

  cdk-mintd:
    build:
      context: ./mint
      dockerfile: Dockerfile
    environment:
      # General mint config
      MINT_HTTP_BIND: 0.0.0.0:8080
      MINT_DATA_DIR: /data
      # LDK / Lightning config (Mutinynet)
      LDK_NETWORK: mutinynet
      LDK_ESPLORA_URL: ${LDK_ESPLORA_URL:-https://mutinynet.ltbl.io/esplora}
      LDK_RGS_URL: ${LDK_RGS_URL:-wss://mutinynet.ltbl.io/ldk-rgs}
      LDK_PERSISTENCE_DIR: /data/ldk
      LDK_BLOCKCHAIN_BACKEND: esplora
      # Seed/material
      LDK_SEED_HEX: ${LDK_SEED_HEX:-0000000000000000000000000000000000000000000000000000000000000001}
      # Optional Tor/Proxy can be added here
    volumes:
      - mint-data:/data
    ports:
      - "8080:8080"

  auth-gateway:
    build:
      context: ./auth-gateway
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      TARGET_BASE_URL: http://cdk-mintd:8080
      OIDC_ISSUER: http://keycloak:8080/realms/mandel
      OIDC_AUDIENCE: mandel-gateway
      OIDC_JWKS_URI: http://keycloak:8080/realms/mandel/protocol/openid-connect/certs
      BLACKLISTED_EMAILS: ${BLACKLISTED_EMAILS:-bad1@example.com,bad2@example.com}
      REQUIRE_EMAIL_VERIFIED: ${REQUIRE_EMAIL_VERIFIED:-false}
    depends_on:
      - cdk-mintd
      - keycloak
    ports:
      - "3000:3000"

volumes:
  keycloak-pgdata:
  mint-data:

