version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: mandel-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=dev-file
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command: 
      - start-dev
      - --import-realm
    networks:
      - mandel-network

volumes:
  keycloak_data:

networks:
  mandel-network:
    driver: bridge
